version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./private:/etc/nginx/private
    ports:
      - "443:443"
    depends_on:
      - backend
